
name: Platform Tests
on: [push, pull_request]
permissions:
  contents: read

jobs:
  platform_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.14, 1.18]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install bsdiff

    - name: Test
      run: go test -tags ci ./...

    - name: Update coverage
      run: |
        go get github.com/mattn/goveralls
        set -e
        go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
      if: ${{ runner.os == 'Linux' }}

    - name: Update PR Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
      if: ${{ runner.os == 'Linux' && matrix.go-version == '1.18' }}
